### ISSUE TITLE
请教个关于 bos 参数的问题

### ISSUE THREAD

**Issue by iLampard** [yangalan123/anhp-andtt#1]
你好，请教个关于代码细节的问题。

在 manager.py 中加载数据的时候 add_bos=False, 但是在模型中却强制写成 add_bos=True，我改成 add_bos=False会报错。

dataset = NHPDataset(_data[_split], event_types, concurrent=False, add_bos=False, add_eos=False)
line 35，https://github.com/yangalan123/anhp-andtt/blob/master/anhp/esm/manager.py

self.add_bos = True
line 64，https://github.com/yangalan123/anhp-andtt/blob/master/anhp/model/xfmr_nhp_fast.py

从我个人理解来看，model.add_bos 和 dataset.add_bos 含义不一样对吗？ model.add_bos 是指每次预测下一个点，所以label序列的长度比输入序列的长度要少一个，后面代码会因此有特殊的处理。

如果我的理解正确的话，那是不是所有的模型 model.add_bos 都应该是 True，这样代码里面一些 if else 的判断就不需要了，比如
line 158-165, https://github.com/yangalan123/anhp-andtt/blob/master/anhp/model/xfmr_nhp_fast.py，这部分实际上都不会执行。

非常感谢。

**Comment by yangalan123** [comment]
您好，非常感谢您对我们工作的关注，您提到的这个问题确实是一个比较难理解的地方，我的解释如下：

关于model.add_bos和dataset.add_bos：如您所说，他们的behavior确实不同，dataset.add_bos说的是要不要在每个sequence上prepend一个bos token(t=0)，model.add_bos指的是model对于加不加bos的情况做特殊处理，model.add_bos=False是一个早期的code版本的feature，后来由于需要与THP (Zuo et al., 2020) 和SAHP (Zhang et al., 2020) 等直接从第二个token开始evaluate的model进行对比，我后续对于code的开发都建立在model.add_bos=True的基础上，我后续会找时间进行double-check看看原来的选项是否还能work out并且会及时通知您。

**Comment by iLampard** [comment]
好的，感谢回复。我也在清理这块的代码，希望把tpp的几个经典模型放到同一个框架里面，方便对比和调试。到时候会开源出来供大家试用。
