### ISSUE TITLE
What are the corrections to the originals?

### ISSUE THREAD

**Issue by kevindoran** [yangalan123/anhp-andtt#6]
Would you be able to give some details on what exactly the corrections are, and the motivations for them?

**Comment by yangalan123** [comment]
Thanks for your interest! It is a bit complicated as there are many important details, and I have not worked in this direction for a while (roughly two years). The main changes we implemented are: 1) we fixed index mismatch issues in THP and SAHP in model implementation and input processing codes, and 2) we also implemented a more principled though more expensive thinning algorithm in inference. 

By the way, this project is currently in an archival mode, and [EasyTPP](https://github.com/ant-research/EasyTemporalPointProcess) provides more up-to-date, efficient, and easy-to-use implementations for SAHP, THP, and ANHP models in this repo. I highly recommend checking that one out to get better support.

**Comment by hongyuanmei** [comment]
I am confused.

They have a bug. We fixed it.

Why do you have write this much to explain this?

You also said "not really correction". It is really correction, right? If
fixing a bug is not a correction, what is it?

Hongyuan

**Comment by hongyuanmei** [comment]
> Thanks for your interest! It is a bit complicated as there are many important details, and I have not worked in this direction for a while (roughly two years). I can only recall some high-level summary of what's changed below and hopefully that is helpful. We intentionally keep the package of THP/SAHP similar to their original repo, so you can run diff to know more specific changes. By the way, this project is currently in an archival mode, and [EasyTPP](https://github.com/ant-research/EasyTemporalPointProcess) provides more up-to-date, efficient, and easy-to-use implementations for SAHP, THP, and ANHP models in this repo. I highly recommend checking that one out to get better support.
> 
> High-level intuition: the main problem we found when we were reproducing the benchmark results in SAHP and THP papers, was that there were problems in their input processing and/or attention map computation -- as these models are autoregressive Transformer models, each position should exactly only "see" and process information from preceding positions, **including the current token itself** (e.g., k -th position should only see preceding k − 1 inputs, and should have zero information for k , k + 1 , . . . L -th inputs (type + time) ). Otherwise, there is a risk that models predict the next step (type and time) when the models already "see" it, and the benchmark performance can be unreliable. As we explained in README, we have discussed and reported the problem we found with the SAHP and THP authors and obtained the permissions to release our corrected version.
> 
> Though not really "corrections", to ensure a fair comparison, we also implement a more principled (though more expensive) thinning algorithm for inferring future events in evaluation. See #5 for a more detailed discussion.

The index mismatch is a bug, and we fixed it, right?

Why did you say "not really correction"? It is really a correction, right?

**Comment by yangalan123** [comment]
> The index mismatch is a bug, and we fixed it, right?

Yes. 

> Why did you say "not really correction"? It is really a correction, right?

I agree with you.

**Comment by hongyuanmei** [comment]
> > The index mismatch is a bug, and we fixed it, right?
> 
> Yes.
> 
> > Why did you say "not really correction"? It is really a correction, right?
> 
> I agree with you.

Thanks. Then can you revise your answer to make it clear to @kevindoran 

Simply explain what the bug is, and how we fixed it. 

Thanks!

**Comment by yangalan123** [comment]
Fixed it. Thanks for reminding me about this! It was hard for me to recall these details and I apologize for any confusion.

**Comment by kevindoran** [comment]
Thank you @yangalan123 and @hongyuanmei for the reply!
