### ISSUE TITLE
Incorrect log-likelihood computation in THP

### ISSUE THREAD

**Issue by AnthonyChouGit** [yangalan123/anhp-andtt#7]
The intensity of each event should be calculated using the last hidden state with an extrapolation rule given by equation (6) in the original paper. Instead, you are using the current hidden state without temporal extrapolation. This does not make sense. This error comes from the original repository but has not been fixed in this implementation.
https://github.com/yangalan123/anhp-andtt/blob/bf8708631cf9ab67a0b682a5a784025b75d0602c/thp/thp_training/Utils.py#L58

This is illustrated in an issue from the original repository:
https://github.com/SimiaoZuo/Transformer-Hawkes-Process/issues/10#issuecomment-1321651287

**Comment by yangalan123** [comment]
Hi, thanks for the issue. First, I have to clarify that I am not working in the TPP field so my answer might be wrong. Feel free to point out any problem that I may have. Second, as far as I can tell, I think the `compute_integral_unbiased()` [this line](https://github.com/yangalan123/anhp-andtt/blob/bf8708631cf9ab67a0b682a5a784025b75d0602c/thp/thp_training/Utils.py#L77C20-L77C45) conduct the temporal extrapolation as you suggest. You can take a look at the implementation of this function [here](https://github.com/yangalan123/anhp-andtt/blob/bf8708631cf9ab67a0b682a5a784025b75d0602c/thp/thp_training/Utils.py#L38), the temporal extrapolation is implemented as first compute the `diff_time` and then compute `all_lambda` using softplus function. Let me know if there is any further problem.

**Comment by AnthonyChouGit** [comment]
> Hi, thanks for the issue. First, I have to clarify that I am not working in the TPP field so my answer might be wrong. Feel free to point out any problem that I may have. Second, as far as I can tell, I think the `compute_integral_unbiased()` [this line](https://github.com/yangalan123/anhp-andtt/blob/bf8708631cf9ab67a0b682a5a784025b75d0602c/thp/thp_training/Utils.py#L77C20-L77C45) conduct the temporal extrapolation as you suggest. You can take a look at the implementation of this function [here](https://github.com/yangalan123/anhp-andtt/blob/bf8708631cf9ab67a0b682a5a784025b75d0602c/thp/thp_training/Utils.py#L38), the temporal extrapolation is implemented as first compute the `diff_time` and then compute `all_lambda` using softplus function. Let me know if there is any further problem.

Thanks for your reply. The code you quote is used to compute the integral compensation term of the following log-likelihood. Note that you are calculating the i-th log intensity term [here](https://github.com/yangalan123/anhp-andtt/blob/bf8708631cf9ab67a0b682a5a784025b75d0602c/thp/thp_training/Utils.py#L67) using the i-th hidden state instead of predicting it from the (i-1)-th hidden state and considering the time interval. 

$$
 \mathcal{L}(\mathcal{S})=\sum_i \log \lambda_{k_i}(t_i)-\int_0^T\lambda(\tau)d\tau
$$

EasyTPP does it the right way [here](https://github.com/ant-research/EasyTemporalPointProcess/blob/d4731ddd07cd5c0a3a5faf30b728daa0b075b951/easy_tpp/model/torch_model/torch_thp.py#L105). I suggest citing the EasyTPP repository in your README as a more sophisticated implementation for training and testing.

**Comment by yangalan123** [comment]
Thanks for following up and providing the correction! I would cite EasyTPP as a more sophisticated implementation in README.  A few other issues mentioned that repo and I think it is now a good time to refer people to EasyTPP.  It seems they do have better support and implementation. This repo will go under archival mode therefore and I hope people working on TPP can get their problems solved there.
